name: Format

on:
  workflow_dispatch:

jobs:
  format:
    uses: L3DigitalNet/project-standards/.github/workflows/format.yml@v5
    with:
      prettier: false
      globs: "**/*.md\n**/*.json\n**/*.jsonc\n**/*.yml\n**/*.yaml"
      exclusions: ""
