name: Validate project standards

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  frontmatter:
    name: Frontmatter
    uses: L3DigitalNet/project-standards/.github/workflows/validate-markdown-frontmatter.yml@v5
permissions:
  contents: read
